### ISSUE TITLE
nice job!

### ISSUE THREAD

**Issue by ephemeral242** [SlyBouhafs/MMMKIII#4]
Thanks for the great work done with the script!

great job!!

My question is if you think it could work with "Akai mpk mini plus", or if you think some modification should be made to the script.

thank you so much!!

**Comment by SlyBouhafs** [comment]
Hi @ephemeral242 ! 
I am not sure if it would work for the MPK Mini Plus, the programs that i made are specifically designed to be used on the MPK Mini MKIII. If the two are similar, you can try flashing the programs but at your own risk, i won't be able to help you.
What makes the script actually work is just assigning the right CC commands with the right midi note in the [settings.py](https://github.com/SlyBouhafs/MMMKIII/blob/master/settings.py) file.
